name: InvisibleArmor
main: cl.netgamer.showskin.SS
version: 2

commands:
   showskin:
      description: show your skin by hiding your armor while not taking damage (/ss command).
      usage: type "/ss" command to hide your armor ("show skin" or "save suit")
      aliases: [ss,invisiblearmor,invisarmor,ia]

# aqui tambien se configuran los permisos (ya no?)
# no usar la letra enye
